[package]
name = "eeg_ml"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.15"
linfa = "0.6"  # Machine Learning framework
ort = "1.15"  # ONNX Runtime for Rust
ndarray = "0.15"  # Handling NumPy-like arrays
libc = "0.2"  # Required for FFI
